# Generated by Django 4.1.6 on 2023-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_title', models.CharField(max_length=250)),
                ('my_wish', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='wishFormModel',
        ),
    ]
