<CanvasExample3>:
    canvas:

        Color: 
            rgb: 0, 0, 1
        Line:
            circle: (200, 200, 100) #center_x, center_y, radius
            width: 2
        
        Color: 
            rgb: 0, 1, 0
        Line:
            ellipse: (500, 300, 100, 200) #center_x, center_y, radius_x, radius_y
            width: 4

        Color: 
            rgb: 1, 0, 0
        Line:
            rectangle: (800, 100, 300, 200) #x, y, width, height
            width: 2